version: '3.1'
services:
#   web:
#     build: ./quiz-manager-frontend/
#     ports:
#         - 4200:4200
#     depends_on:
#         - "app"
#   app:
#     build: ./quiz-managment-backend/
#     ports:
#         - 8085:8085
#     depends_on:
#         - "db"
  db:
    image: postgres:alpine
    container_name: postgresDatabase
    environment: 
        POSTGRES_USER: 'unicorn_user'
        POSTGRES_PASSWORD: 'magical_password'
        POSTGRES_DB: 'quiz_management_db'
    volumes:
        - db-data:/var/lib/postgresql/data
        - ./SQL-Scripts/init.sql:/docker-entrypoint-initdb.d/init.sql
    ports:
        - 5433:5432
volumes:
    db-data: